### ISSUE TITLE
Make pywal run on start

### ISSUE THREAD

**Issue by spiwocoal** [manilarome/Glorious-Dotfiles#26]
I've been trying to add pywal to this rice, but I can't quite get it to run on start, I've added `wal -R` to `run_on_startup` in the file `~/.config/awesome/configuration/apps.lua`, but it doesn't seem to work. Could someone help me with this please?

I'm using the floppy theme btw.

EDIT: It doesn't set the wallpaper either, even when just running it directly from the terminal

**Comment by manilarome** [comment]
I assume you're using the stable version of pywal? If yes, install the [pywal-git master](https://github.com/dylanaraps/pywal) branch.

I never tried pywal, but installed it anyway. Reproduced the issue so I inspect the source code and found this: 
The stable one have this in `wallpaper.py`:
```python
util.disown(["awesome-client", "gears.wallpaper.maximized(", img, ")"])
```

While the git master branch have:
```python
        util.disown(["awesome-client",
                     "require('gears').wallpaper.maximized('{img}')"
                     .format(**locals())])
```

Sooo... it's safe to assume that your problem will be fixed by using the **git-branch**. Hope it helps!

**Comment by spiwocoal** [comment]
I thought the same thing, but the git branch doesn't seem to fix the issue, the wallpaper isn't set either.
The colorscheme is changed though.

**Comment by manilarome** [comment]
> the wallpaper isn't set either.

It's working. Maybe because the wallchange.lua module sets the wallpaper on startup. try disabling it in rc.lua. I'm using `wal 3.3.1` git

**Comment by spiwocoal** [comment]
Never mind, I fixed it.
The problem was that as I'm using XFCE + Awesome, wal was trying to set XFCE's wallpaper instead of Awesome's, because it had higher preference in the function's if, so I just commented out the part where wal sets the wallpaper for XFCE.
